/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * phi_p5_d1_c0.c
 *
 * Code generation for function 'phi_p5_d1_c0'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "phi_p5_d1_c0.h"

/* Function Definitions */
real_T phi_p5_d1_c0(const emlrtStack *sp, real_T gi)
{
  real_T phiOut;
  real_T t7;
  real_T t11;
  real_T t14;
  real_T phiOut_tmp;
  (void)sp;

  /* PHI_P5_D1_C0 */
  /*     PHIOUT = PHI_P5_D1_C0(GI) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.3. */
  /*     10-Apr-2019 09:50:27 */
  t7 = gi * gi;
  t11 = (gi + 1.0) * (gi + 1.0);
  t14 = (gi - 1.0) * (gi - 1.0);
  if ((-3.0 < gi) && (gi <= -2.0)) {
    phiOut_tmp = (((gi + 1.0) + 1.0) + 1.0) * (((gi + 1.0) + 1.0) + 1.0);
    phiOut = (((gi + 1.0) + 1.0) * phiOut_tmp * ((((gi + 1.0) + 1.0) + 1.0) +
               1.0) * (((((gi + 1.0) + 1.0) + 1.0) + 1.0) + 1.0) *
              -0.013888888888888888 + ((gi + 1.0) + 1.0) * ((gi + 1.0) + 1.0) *
              phiOut_tmp * ((((gi + 1.0) + 1.0) + 1.0) + 1.0) * (((((gi + 1.0) +
      1.0) + 1.0) + 1.0) + 1.0) / 72.0) - (gi + 1.0) * (((gi + 1.0) + 1.0) *
      ((gi + 1.0) + 1.0)) * phiOut_tmp * ((((gi + 1.0) + 1.0) + 1.0) + 1.0) *
      (((((gi + 1.0) + 1.0) + 1.0) + 1.0) + 1.0) / 180.0;
  } else if ((-2.0 < gi) && (gi <= -1.0)) {
    phiOut_tmp = ((gi + 1.0) + 1.0) * ((gi + 1.0) + 1.0);
    t14 = phiOut_tmp * (((gi + 1.0) + 1.0) + 1.0) * ((((gi + 1.0) + 1.0) + 1.0)
      + 1.0);
    phiOut = (((t14 / 24.0 - ((gi + 1.0) + 1.0) * (((gi + 1.0) + 1.0) + 1.0) *
                ((((gi + 1.0) + 1.0) + 1.0) + 1.0) / 24.0) + (gi + 1.0) *
               phiOut_tmp * (((gi + 1.0) + 1.0) + 1.0) * ((((gi + 1.0) + 1.0) +
      1.0) + 1.0) * 0.069444444444444448) - t14 * t11 * 0.069444444444444448) +
      gi * phiOut_tmp * (((gi + 1.0) + 1.0) + 1.0) * ((((gi + 1.0) + 1.0) + 1.0)
      + 1.0) * t11 / 36.0;
  } else if ((-1.0 < gi) && (gi <= 0.0)) {
    phiOut_tmp = ((gi + 1.0) + 1.0) * (((gi + 1.0) + 1.0) + 1.0);
    t14 = phiOut_tmp * t7;
    phiOut = ((((gi + 1.0) * ((gi + 1.0) + 1.0) * (((gi + 1.0) + 1.0) + 1.0) /
                3.0 - phiOut_tmp * t11 / 6.0) - gi * ((gi + 1.0) + 1.0) * (((gi
      + 1.0) + 1.0) + 1.0) * t11 * 0.1388888888888889) + t14 * t11 *
              0.1388888888888889) - t14 * (gi - 1.0) * t11 / 18.0;
  } else if ((0.0 < gi) && (gi <= 1.0)) {
    phiOut_tmp = (gi + 1.0) * ((gi + 1.0) + 1.0) * t7;
    phiOut = (((((gi + 1.0) * ((gi + 1.0) + 1.0) / 2.0 - gi * (gi + 1.0) * ((gi
      + 1.0) + 1.0) * 0.75) + phiOut_tmp / 4.0) + phiOut_tmp * (gi - 1.0) *
               0.1388888888888889) - phiOut_tmp * t14 * 0.1388888888888889) +
      phiOut_tmp * ((gi - 1.0) - 1.0) * t14 / 18.0;
  } else if ((1.0 < gi) && (gi <= 2.0)) {
    phiOut_tmp = gi * (gi + 1.0) * (((gi - 1.0) - 1.0) * ((gi - 1.0) - 1.0));
    phiOut = ((((((gi + 1.0) - gi * (gi + 1.0)) + gi * (gi + 1.0) * (gi - 1.0) *
                 0.66666666666666663) - gi * (gi + 1.0) * t14 / 6.0) - gi * (gi
                + 1.0) * ((gi - 1.0) - 1.0) * t14 * 0.069444444444444448) +
              phiOut_tmp * t14 * 0.069444444444444448) - phiOut_tmp * (((gi -
      1.0) - 1.0) - 1.0) * t14 / 36.0;
  } else if ((2.0 < gi) && (gi <= 3.0)) {
    phiOut_tmp = gi * (gi - 1.0);
    t14 = phiOut_tmp * (((gi - 1.0) - 1.0) * ((gi - 1.0) - 1.0));
    t7 = t14 * ((((gi - 1.0) - 1.0) - 1.0) * (((gi - 1.0) - 1.0) - 1.0));
    phiOut = (((((-(gi - 1.0) + phiOut_tmp / 2.0) + t14 / 24.0) - phiOut_tmp *
                ((gi - 1.0) - 1.0) * 0.20833333333333334) + t14 * (((gi - 1.0) -
      1.0) - 1.0) / 72.0) - t7 / 72.0) + t7 * ((((gi - 1.0) - 1.0) - 1.0) - 1.0)
      / 180.0;
  } else {
    phiOut = 0.0;
  }

  return phiOut;
}

/* End of code generation (phi_p5_d1_c0.c) */
